### ISSUE TITLE
Should Pygeoprocessing have an Error Class?

### ISSUE THREAD

**Issue by dcdenu4** [natcap/pygeoprocessing#103]
When working on a more uniform approach for how InVEST models do raster reclassification and report errors to users, I noticed that `reclassify_raster` could potentially raise 3 different `ValueError`s. `geoprocessing.py` in general has 51 occurrences of `raise ValueError`. It got me wondering if using the standard exception classes for module related errors is the right approach. It seems that in some of the `ValueError` instances, the errors do not actually fit the description of `ValueError` and it obfuscates uncaught `ValueErrors` from module raised Errors based on a conditional that was not met in the API contract. 

One thing I thought might be a clean solution for the mentioned uniforming of InVEST reclassification tasks and error messages was to add a `try/except` around the `reclassify_raster` call that handled the raised `ValueError` from `reclassify_raster` by providing it's own custom error message as to better help users running specific models. However, since `reclassify_raster` could potentially raise `ValueError` 3 times that solution is not possible. Also in doing so I run the risk of capturing a `ValueError` that was NOT explicitly raised by the geoprocessing module. If however, `reclassify_raster` raised a `ReclassificationValueError` (or something similar) it is both much more descriptive and easy to create a `try/except` flow around. I'm not saying this SHOULD be the approach InVEST uses for the particular reclassification issue, but I am asking: are we using Python exceptions properly?

Built in Exceptions Python 3.8
https://docs.python.org/3/library/exceptions.html#bltin-exceptions
User Defined Exceptions Python 3.8
https://docs.python.org/3/tutorial/errors.html#tut-userexceptions

**Comment by richpsharp** [comment]
Short answer: Are we using Python exceptions properly? Yes. But that doesn't mean we can't make custom exceptions. In this case we might be fine though. 

Note that only one `ValueError` is explicitly documented in `reclassify_raster` because it's the kind of error that can't be pre-checked without running through the whole raster once to begin with. It would potentially double computation time to check for that so that's why we hide it in this function. It's documented to show that the API user can rely on that exception to occur on the complicated case of a missing value in a raster.

The other two are convenience error checks that really only occur at a programmer error level. If InVEST is passing something that's not a raster path/band tuple or an empty reclassification map, that's something that InVEST should really check for. There shouldn't be a direct user path that makes an invalid raster path/band tuple or an empty value map unless there's a bug in InVEST.

So, if you're worried about this, think about it in terms of a programming by contract. As the API user you should ensure that the variables are in the correct states before invoking the call, except it's okay for you to rely on the ValueError for a missing pixel value because that's documented. 

If I were to redesign this I like the idea of a custom exception for those first case, something like "NoPathBandTupleError" since it's so common in PyGeoprocessing. That'd be something you'd never explicitly catch because it meant that you programmed it wrong to begin with and it'd also mean you could benefit from that custom class without importing a whole custom exception ecosystem. I'd also relax that condition on "one value required" an eliminate that exception entirely. Either way, at the API level you should be programming by contract and only worrying about that one ValueError.

So that's a long answer to say that considering what exceptions should be raised is a great and careful one. It really makes you think about what a function should be doing and how its expected to be used. If we did have a case where we could raise two distinct errors and it was important to differentiate between them it might make sense to have a custom exception class. If you're going through PyGeoprocessing you might see stuff like that, but I don't think it exists for `reclassify_raster`. And honestly if you do see a multiple error path it might mean that function is non-orthogonal and doing too many things. Dunno --we'll see?

At any rate, does that seem reasonable at the InVEST level? Check your contract for the things that aren't explicitly documented as raising a ValueError? Then it's okay to handle the ValueError as a missing value in the raster?

And also if there are error behaviors that you need to catch at the API level that aren't easily differentiable with the built in Python classes, lets add them. I'll make an issue to add a `NoPathBandTupleError` class.

**Comment by dcdenu4** [comment]
Hey Rich,

Thanks for that response! That is super helpful and I love thinking about these things to help build my software engineering understanding. I started in on this thought thread as I was trying to use ValueError from the reclassify function, but wasn't sure if I was doing something wrong by not looking out for the other ValueError's in there. Then I started searching around to learn all I could on Python exception handling. I think you've clarified things pretty well and it seems to jive with what I'm "re-learning" in pragmatic programmer 20th anniversary, so that's fun!

I'll mark this as closed.
