### ISSUE TITLE
Add MFD Watershed Delineation

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#145]
Considering that most of the routed models in InVEST use MFD watershed delineation, it's reasonable to want to aggregate results by watersheds generated from MFD flow direction.

**Comment by richpsharp** [comment]
This is something Rafa has said there's no support in the hydrological research community. In practice when we've published global results run with MFD we've had to re-run them with D8 to be comparable to others. I find that disappointing, but in that context there's no need to develop and implement that algorithm for pygeoprocessing.

In other words, it's intentional we don't have this.

Feel free to reopen if there's context that I'm missing or don't understand!
