### ISSUE TITLE
possible addition to align_and_resize_raster_stack

### ISSUE THREAD

**Issue by emlys** [natcap/pygeoprocessing#176]
While working on the stormwater model I looked for this feature and realized it doesn't exist. For `align_and_resize_raster_stack`, it could be nice to have the option to set a new `NODATA` for each aligned raster. `align_and_resize_raster_stack` could have a new arg `target_nodata_list` which could be `None` (don't change the nodata) or a list (set the nodata for each raster). 
Using a global `NODATA` throughout the model is handy because you get shorter function signatures (don't have to pass in the `NODATA` for every array) and there's less room for error. Overwriting the input rasters to have this same global `NODATA` would simplify things even more. And since we're already creating modified copies in `align_and_resize_raster_stack`, the additional work is minimal.
@richpsharp what do you think?

**Comment by richpsharp** [comment]
Hi @emlys, it's an alluring idea to make all input rasters have the same nodata value. I agree that can be annoying. There's some things I'd think about first:

* Setting a new nodata value requires iterating over the raster and changing the current nodata value to a new nodata value, aside from a call to `SetNodataValue` for the band. There wouldn't be any computational savings by doing this in `align_and_resize_raster_stack` since the primary function there is to warp each raster. It'd require a warp then an iterblocks, and not clear which one to do first since if you have a change in resolution you might want to do the low first then warp to high? 
* Along those lines, I feel like this operation is non-orthogonal to the functionality in `align_and_resize_raster_stack`. I understand it would be convenient to have one function there, but you'd be doing two separate raster operations and you would need an intermediate file that would need to be deleted. I don't see a computational advantage for nesting such an operation inside  `align_and_resize_raster_stack`.

So given those two things I don't thing adding an operation in `align_and_resize_raster_stack` is the right place, but I'd also consider the usefulness of such a general function. 

* There are cases where it wouldn't make sense to have the same nodata value for every raster. Such as a raster that has no nodata value defined because it uses all the values, such as in a byte sized lulc map. There could be a case where the same nodata value would collide, like a byte mask that uses 2 for nodata 0 for "false' and 1 for 'true' mixed with a flow accumulation raster that requires all positive values to be valid... things like this. I'd just want to be careful about setting up an easy way to do something that might end up creating another problem that's just as annoying as having different nodata values.
* And along those lines, and I mentioned earlier, such an operation would require iterating over the entire raster and changing contents of it just to change a nodata value that's already valid. As a programmer, I would prefer to keep track of the extra parameter of complexity to avoid just iterating over a raster to change one constant to another even while noting it makes my code a little uglier than it could... Then again, handling the cases above would also add new complexity to your code and that might be a lot to ask for just to not have an extra parameter there...

Anyway, those are just some thoughts I have... what do you think?

**Comment by emlys** [comment]
Thanks for the thorough response @richpsharp! James pretty much convinced me this wasn't a great idea and you make good points too. In the stormwater PR I got rid of the one global `NODATA` value and now I have globals for different dtypes: `FLOAT_NODATA = -1`, `UINT8_NODATA = 255`, etc. which accomplishes the goal of keeping them organized while still using the smallest possible dtype. And I agree it's not worth it to overwrite the input rasters just for this.
