### ISSUE TITLE
Remove base_projection_wkt option?

### ISSUE THREAD

**Issue by emlys** [natcap/pygeoprocessing#219]
`warp_raster` has an optional kwarg `base_projection_wkt`, and `align_and_resize_raster_stack` has a similar `base_projection_wkt_list` option, to use in place of the projection defined in the base raster's metadata. I'm guessing this is there in case a raster's projection is known, but not set. We do not use these options anywhere in invest.

imo, pygeoprocessing functions should assume that a correct projection is defined in the metadata, and not have this extra option. Is there a use case for this that I'm missing?

**Comment by emlys** [comment]
Also, `warp_raster` has the kwarg `vector_mask_options` that's used only once in Wind Energy. Propose removing this because as far as I can tell there's no advantage to including masking in the warp operation (current implementation just calls `pygeoprocessing.mask_raster` on the output) and it makes up a large part of the `warp_raster` code.

**Comment by emlys** [comment]
Maybe it would be worth doing a general review of what pygeoprocessing functions and options are used in invest. When we change how invest uses pygeoprocessing, we rarely consider if the pygeoprocessing API should update accordingly. Probably are some other things like this, that had more use cases in the past.

**Comment by phargogh** [comment]
> I'm guessing this is there in case a raster's projection is known, but not set. We do not use these options anywhere in invest.

Yep, exactly right.  Check out the list of drivers at https://gdal.org/drivers/raster/index.html.  There are at least 26 formats (many of which have built-in support in GDAL) that do not support georeferencing at all, and there are others (like the [Arc/Info ASCII Grid](https://gdal.org/drivers/raster/aaigrid.html#raster-aaigrid)) where support for projections is present, but limited.  In both those cases, the user would need to have preexisting knowledge of the projection that is not possible to represent in the file format.

I don't remember the specifics about this particular parameter, but when we did the 2.0 API design, there wasn't anything in there that hadn't proven to be useful.  I betcha that there's some case in Rich's work (maybe in the IPBES analysis?) where this turned out to be very useful.

> Also, `warp_raster` has the kwarg `vector_mask_options` that's used only once in Wind Energy. Propose removing this because as far as I can tell there's no advantage to including masking in the warp operation (current implementation just calls `pygeoprocessing.mask_raster` on the output) and it makes up a large part of the `warp_raster` code.

There's a little bit of history to why there's a vector mask in `warp_raster`: `mask_raster` is more reliable than the GDAL-provided `cutline` functionality that _is_ a part of `gdal.Warp` and is supposed to do the same thing.  By "reliable", I mean that if we pass an invalid geometry object to `gdal.Warp`, it won't actually mask the final result.  But `mask_raster`'s approach _does_ work _even_ on invalid geometry (turns out that GDAL's rasterization is quite resilient to invalid geometries), so we have that included here in this function.

Given all of that, there's still the outstanding question of _should_ this behavior even be an option when it'd be more orthogonal to just require the user to call `mask_raster` in a second step.  I'm not opposed to this, BUT that's a breaking API change that we should be careful about rolling out.

> Maybe it would be worth doing a general review of what pygeoprocessing functions and options are used in invest. When we change how invest uses pygeoprocessing, we rarely consider if the pygeoprocessing API should update accordingly. Probably are some other things like this, that had more use cases in the past.

Maybe!  But we should also be careful to not couple the two projects.  `pygeoprocessing` was for sure spun out of the InVEST development effort and InVEST continues to be one of the biggest consumers of pygeoprocessing's API, but that doesn't mean that InVEST is (or should be) the only project that uses it.

**Comment by dcdenu4** [comment]
>Also, warp_raster has the kwarg vector_mask_options that's used only once in Wind Energy. Propose removing this because as far as I can tell there's no advantage to including masking in the warp operation (current implementation just calls pygeoprocessing.mask_raster on the output) and it makes up a large part of the warp_raster code.

I'm currently using it for processing data on the global viewer project! This is a non InVEST case which I think is likely to become more of our workflow in the future. Here's how I'm using it:

```python
    # Protect against the clipping feature bb being outside the extents of 
    # the raster. ``feature_bb`` is from a polygon.
    target_bb = pygeoprocessing.merge_bounding_box_list(
        [feature_bb, raster_info['bounding_box']], 'intersection')

    clipped_raster_path = os.path.join(
        working_dir, f'clipped_raster_{feature_info[0]}')

    vector_options = {
            'mask_vector_path': input_vector_path,
            'mask_vector_where_filter':f"{attr_key}='{feature_info[0]}'"
            }

    pygeoprocessing.align_and_resize_raster_stack(
        [input_raster_path], [clipped_raster_path], ['near'],
        raster_info['pixel_size'], target_bb,
        vector_mask_options=vector_options)
```

My use case above could certainly be streamlined by just calling `warp_raster` (since I'm only passing in one raster). I think originally I did have multiple rasters I was trying to operate on... But basically the issue I was trying to solve was: given a global country polygon, clip a raster to a specific country bounding box and mask the raster. You could imagine I might have many rasters I'd like to do this operation on at once. Certainly I could do the masking for each warped output raster that comes out of `align_and_resize_raster_stack` in a second step, but I think there's value in this "seemingly" being one operation.

**Comment by dcdenu4** [comment]
I certainly believe in fixing broken windows and keeping code orthogonal where appropriate but I'd also shy away from removing features if they are well documented, require no extra maintenance, and removing the feature doesn't have an improvement benefit. Mostly because of workload and thinking about priorities for the best use of our time. Those are my quick thoughts!

**Comment by emlys** [comment]
Thanks for all the feedback! It sounds like there are good reasons to leave this alone for now, so I'm going to close the issue. 

> There are at least 26 formats (many of which have built-in support in GDAL) that do not support georeferencing at all

Do we handle these in InVEST? I think most models depend on having some georeference. Will they fail validation?

> Given all of that, there's still the outstanding question of should this behavior even be an option when it'd be more orthogonal to just require the user to call mask_raster in a second step. I'm not opposed to this, BUT that's a breaking API change that we should be careful about rolling out.

I'd be in favor of this API change but agree with Doug this isn't a priority to do now.
