### ISSUE TITLE
Improve support for signed byte rasters in reclassification

### ISSUE THREAD

**Issue by phargogh** [natcap/pygeoprocessing#42]
Some time ago in a forums post (https://community.naturalcapitalproject.org/t/habitat-q-error/431/15), I helped a user with a reclassification issue in the InVEST Habitat Quality model that ended up being a bug in how GDAL was handling signed byte rasters and how `reclassify_raster` was handling nodata values.

In order to do this well (and in part because I looked at this issue some time ago), we need to better understand how `reclassify_raster` handles signed byte rasters and the nodata values themselves.

**Comment by richpsharp** [comment]
hi @phargogh, I'm going through the pgp issue queue and tried to see if I could identify this problem. Just from the forum posts I'm not sure exactly the values that were at play, but in an attempt to recreate the issue I made a test that reclassifies a signed byte raster with a negative nodata value and negative valid values and wasn't able to reproduce any issues. Maybe we fixed this somehow? Could you take a look at my test in this branch: https://github.com/richpsharp/pygeoprocessing/tree/bugfix/GEOPROCESSING-42-reclassify-signed/ here: `tests/test_geoprocessing.py::PyGeoprocessing10::test_reclassify_signed_byte_raster` and see if I was doing it right? If you think the issue is still there can you post me the user's data or more information? Or if it looks okay can you mark this issue closed and I'll delete my branch?

**Comment by phargogh** [comment]
Hey @richpsharp I just dug back through my email and found that the user had a malformed LULC raster, where a pixel value of `128` was being used (and was probably supposed to represent nodata), `128` was NOT in the reclassification table (this was InVEST HQ, so the sensitivity table), and the LULC also did not have a defined nodata value.

The raster did happen to be a signed byte raster, so I probably assumed that there was an issue when there wasn't.

**Comment by phargogh** [comment]
While reading through the GDAL docs for a completely different reason, I came across [this tidbit about signed rasters in the GDAL data model description](https://gdal.org/user/raster_data_model.html?highlight=signedbyte#image-structure-domain):

> PIXELTYPE: This may appear on a GDT_Byte band (or the corresponding dataset) and have the value SIGNEDBYTE to indicate the unsigned byte values between 128 and 255 should be interpreted as being values between -128 and -1 for applications that recognise the SIGNEDBYTE type.

So, this is the official GDAL definition of how pixel values should be interpreted, and it also explains why the above behavior was being experienced in `reclassify_raster`: if the nodata value is set to `-1`, GDAL reads that pixel value as `255`, which isn't in the user's table because nodata typically isn't in a user's table.

This is also a problem if someone is working with `raster_calculator` calls and expects to be able to use signed byte pixel values, but is instead handed unsigned byte pixel values.  Since this is an implementation quirk in GDAL, I think pygeoprocessing should handle it so that the values presented to the user are the correct values.

I just got an unsigned byte raster from Stacie that we can use to replicate the issue.

**Comment by phargogh** [comment]
-

**Comment by phargogh** [comment]
After digging into this, it appears that at this time this issue was created, pixel values from signed byte rasters are, in fact, being handled correctly by GDAL (which is great).  The most likely explanation of the bug is that it was the loss of the `SIGNEDBYTE` metadata item after aligning the pixel stack, which of course was addressed in the 2.0 refactor.

I'm going to mark this issue as resolved (since there isn't a technical issue), but I'll also shortly be opening up a PR to explicitly test for the `SIGNEDBYTE` case in `raster_calculator`, for my own sanity.
