### ISSUE TITLE
API website for documentation

### ISSUE THREAD

**Issue by ritviksahajpal** [natcap/pygeoprocessing#47]
Dear Pygeoprocessing team,

Thanks for the great library! I remember that there used to be a website documenting the API, but it does not seem to be around anymore. Is there a link you could point me to that documents the latest API?

**Comment by phargogh** [comment]
Hi @ritviksahajpal, we did indeed have a hosted version of the API documentation around for some time, but abandoned it in advance of the 1.x API refactor.  Hosting the API docs somewhere is on our to-do list, just a lower priority.

In the meantime, you _do_ have a couple of options for taking a look at the API documentation:

1. All functions and classes are all carefully documented ... feel free to just crack open the source code and take a look at the docstrings!  That's how we refer to docstrings ourselves.
2.  If you _really_ want some rendered HTML API documentation, you could always just build a local copy of the API docs with `python setup.py build_sphinx` (assuming you have all of the `pygeoprocessing` dependencies and `sphinx` installed).

Note that the rendered HTML approach includes some of the most-used subpackages and modules of `pygeoprocessing`, there are a few things that are not included there because we haven't been actively maintaining API documentation.  Your best bet for accurate, complete documentation will be to take a look at the source code.

Hope this helps!

**Comment by ritviksahajpal** [comment]
thanks @phargogh !

**Comment by phargogh** [comment]
Sure thing @ritviksahajpal !  I'll leave this issue open as a reminder for us down the road to reestablish automated builds of API documentation.

**Comment by richpsharp** [comment]
Hey @phargogh, in the anticipation of a soonish 2.0 release, I'm the 2.0 milestone for this.  (unless you've got it in a bag already?)

**Comment by phargogh** [comment]
@richpsharp I don't have a prebaked solution ready to go, but the basic infrastructure for HTML API docs is already there.  It should just need some touching up for new functions and/or modules, and its content could use a look-over (and probably trimming, as a lot has changed since the API docs were last published).

**Comment by richpsharp** [comment]
Hi @phargogh, can we revisit this issue again? I'm not opposed to this, but I'd rather not maintain an additional feature that's not useful in the context of our work. This issue is nearly 6 months old so I think it'd be nice to either tuck this in a shoebox somewhere or discuss again. 

Left all to me, I'd archive this and think about it for the "future". If you want to do it, my main concern is another step involved with maintenance during PRs and releases. Here's random stuff I'm thinking about aside from the process of setting all this up and making it automatic
* monitoring changes in Github API... I feel like this has happened before either through how authentication is done or how uploading to websites happen or whatnot. 
* Do Cython docstrings document just fine?
* My offhand experience that automated processes are a little finicky and not so great. I know we can point at a reason these are finicky (moving to github, finding TravisCI not working so well, reliance on third party services/libraries that go temporarily and the actual process of doing a PyGeoprocessing release is not complicated. Basically I'm worried that wrapping all this up in an automated process would mean that there's possible maintenance that's harder than what's already there. 

I realize I could be overthinking this, but just trying to scrub out issues as part of another upgrade effort to functionality in PyGeoprocessing and this one has been sitting for a while. It'd be great if we could yay or nay this and make a loose schedule for implementation if yay. Thanks for checking this again!

**Comment by phargogh** [comment]
Hey @richpsharp , yep, for sure!  I'm still happy to do this, and it shouldn't be too challenging or time-consuming to implement if we stick to what's in the API documentation.  The main things that can be a drag on maintenance are tutorials or other prose content that assume a certain API ... but if we're sticking strictly to auto-generated API documentation, then the python documentation should be the one source of truth and automatically updated.

> monitoring changes in Github API... I feel like this has happened before either through how authentication is done or how uploading to websites happen or whatnot.

For a ReadTheDocs build, this isn't an issue at all since RTD handles all of the appropriate authentication, pulling, cloning, etc, and will build the docs for whatever branches we tell it to.  Once everything is set up, RTD will build the documentation for each push to the designated branch(es).  For pygeoprocessing, I'd set it up to rebuild for each push to `main`.

> Do Cython docstrings document just fine?

Yes!  The details here are that we'll just need to build the package (see this [SO answer](https://stackoverflow.com/a/31882049/299084)) so that the docstrings will be available on package import.  We can work around the GDAL dependency because we dynamically import GDAL when it's needed and it can therefore be mocked out as we do in InVEST's API docs.

> My offhand experience that automated processes are a little finicky and not so great. I know we can point at a reason these are finicky (moving to github, finding TravisCI not working so well, reliance on third party services/libraries that go temporarily and the actual process of doing a PyGeoprocessing release is not complicated. Basically I'm worried that wrapping all this up in an automated process would mean that there's possible maintenance that's harder than what's already there.

The presence of more stuff always implies more maintenance, and API docs are no different.  My hope with using RTD for the API docs is that the actual maintenance that _we'll_ be responsible for will be basically eliminated as it has been for the `natcap.invest` api docs.  That can, of course, change in the future, and we could evaluate at that time if the RTD builds are worth maintaining if we wanted.

The main way that API Docs will affect us in the development of pygeoprocessing is that we'll need to be more careful about having valid RST in our docstrings.  That might end up being annoying.  I can lint this in github actions to make it easier (and I'm planning on doing the same in `natcap.invest` as well).

Also, FWIW, I'm happy to accept maintenance of the API docs for however long I'm at NatCap ... you shouldn't have to be responsible for it.

Anyways, what do you think?

**Comment by richpsharp** [comment]
Sounds great @phargogh, do you know when or how you can prioritize this in the context of everything else you're doing?

**Comment by phargogh** [comment]
I bet this'd take a few hours to set up, but I won't realistically be able to address this until next week at least.  I would expect this to be done in advance of winter break.  How does that sound?

**Comment by richpsharp** [comment]
Great, that sounds totally fine.

**Comment by brylie** [comment]
Remember to add a link to the documentation in the README and probably in the GitHub repository metadata.
